---
# Tasks to create the hardening script
- block:
  - name: Create hardening script
    template:
      src: templates/hardening.sh.tmpl
      dest: "{{ role_path }}/files/{{ vm.name }}-hardening.sh"
  delegate_to: "{{ groups['bastion'][0] if (groups['bastion'] | length >= 1 and bastion.address != [] and bastion.address != ['']) else 'localhost' }}"
  tags: vm_creation
