---
# Tasks to create the hardening script
- name: Create hardening script
  ansible.builtin.template:
    src: templates/hardening.sh.tmpl
    dest: "{{ role_path }}/files/{{ vm.name }}-hardening.sh"
    mode: '644'
  delegate_to: localhost
