---
# Tasks to delete the hardening script
- block:
  - name: delete hardening script locally
    file:
      path: "{{ role_path }}/files/{{ vm.name }}-hardening.sh"
      state: absent
  delegate_to: "{{ groups['bastion'][0] if (groups['bastion'] | length >= 1 and bastion.address != [] and bastion.address != ['']) else 'localhost' }}"
  tags: vm_creation
