---
# tasks file to unset quota
- block:
  - name: disable user quota in grub
    ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=).*$'
      replace: '\g<1>""'
    notify:
      - update grub
      - reboot vm
  - name: disable user quota in /etc/fstab
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^(.* / xfs defaults),uquota (.*)$'
      replace: '\g<1> \g<2>'
  - name: flush handlers
    meta: flush_handlers
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'usrquota' ]
