---
# tasks file to set quota
- block:
  - name: enable user quota in grub
    ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=".*)"$'
      replace: '\g<1> rootflags=uquota"'
    notify:
      - "{{ 'update-grub' if ansible_facts.distribution == 'Ubuntu' else 'grub2-mkconfig' }}"
      - reboot vm
  - name: enable user quota in /etc/fstab
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^(.*\s*/\s*xfs\s*defaults)(\s*.*)$'
      replace: '\g<1>,uquota \g<2>'
  - name: flush handlers
    meta: flush_handlers
  - name: set user quota on /
    ansible.builtin.shell: xfs_quota -x -c 'limit bsoft={{ softlimit }}g bhard={{ hardlimit }}g -d' /
    vars:
      softlimit: "{{ sysconfig.secondary.user_quota if 'dr' in group_names else sysconfig.primary.user_quota }}"
      hardlimit: "{{ softlimit|int + 1 }}"
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'usrquota' ]
