---
# tasks file to set quota
- block:
  - name: enable user quota in grub
    ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=".*)"$'
      replace: '\g<1> rootflags=uquota"'
    notify:
      - "{{ 'update-grub' if ansible_facts.distribution == 'Ubuntu' else 'grub2-mkconfig' }}"
      - reboot vm
  - name: enable user quota in /etc/fstab
    ansible.builtin.replace:
      path: /etc/fstab
      regexp: '^(.*\s*/\s*xfs\s*defaults)(\s*.*)$'
      replace: '\g<1>,uquota \g<2>'
  - name: flush handlers
    meta: flush_handlers
  - name: set user quota on /
    ansible.builtin.shell: xfs_quota -x -c 'limit bsoft={{ softlimit }}k bhard={{ hardlimit }}k -d' /
    vars:
      softlimit: "{{ (sysconfig.secondary.user_quota if 'dr' in group_names else sysconfig.primary.user_quota)|int * 1024|pow(2)|int }}"
      hardlimit: "{{ (softlimit|int + 0.2 * 1024|pow(2))|int }}"
  - name: create /etc/bashrc
    ansible.builtin.file:
      path: '/etc/profile.d/setaliases.sh'
      state: touch
    when: ansible_facts.distribution == 'Ubuntu'
  - name: create an alias for the quota command
    ansible.builtin.lineinfile:
      line: "{{ line_item.toadd }}"
      path: "{{ line_item.filename }}"
    loop:
      - {filename: "{{ '/etc/profile.d/setaliases.sh' if ansible_facts.distribution == 'Ubuntu' else '/etc/bashrc' }}", toadd: "alias myquota=\"xfs_quota -x -c 'quota -h' /\""}
    loop_control:
      loop_var: line_item
  - name: update /etc/motd
    ansible.builtin.copy:
      dest: /etc/motd
      content: "{{ '\n' if ansible_facts.distribution != 'Ubuntu' else '' }}Your home disk quota is 1G\nIf you exceed your quota, you will not be able to log back in\nType \"myquota\" to check your quota\n\n"
  - name: create the transfer directory under {{ vm.disk1_mount }}
    ansible.builtin.file:
      path: "{{ vm.disk1_mount }}/transfer"
      state: directory
      mode: 0777
      owner: root
      group: root
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'usrquota' ]
