---
# tasks file for ldap_integration
- name: Main ldap_integration clock
  when:
    - infra_admin_user != ''
    - join_domain | default(false) | bool or leave_domain | default(false) | bool
  tags: ['never', 'ldap_integration']
  block:
    - name: Checking if VM exists
      block:
        - name: Check if VM exists
          community.vmware.vmware_guest_info:
            hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
            username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
            password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
            datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
            name: "{{ vm.name }}"
            schema: vsphere
            validate_certs: false
          no_log: true
          delegate_to: localhost
      rescue:
        - name: Define creds_status
          ansible.builtin.set_fact:
            creds_status: 'The VM does not exist'
    - name: Check original credentials
      when:
        - creds_status | default('') == ''
      block:
        - name: Check VM credentials
          ansible.builtin.wait_for_connection:
            timeout: 3
          register: jd_vm_creds
          check_mode: false
      rescue:
        - name: Define creds_status
          ansible.builtin.set_fact:
            creds_status: 'The VM IP address is invalid'
          when:
            - jd_vm_creds.msg is defined
            - jd_vm_creds.msg is search('Failed to connect to the host via ssh|Data could not be sent to remote host')
        - name: Check service account credentials
          when:
            - jd_vm_creds.msg is defined
            - jd_vm_creds.msg is search('Invalid/incorrect')
          block:
            - name: Switch to {{ vm_admin_user + ' user' }}
              ansible.builtin.set_fact:
                ansible_user: "{{ vm_admin_user }}"
                ansible_ssh_pass: "{{ vm_admin_pass }}"
                ansible_become_pass: "{{ vm_admin_pass }}"
              no_log: true
            - name: Check updated VM credentials
              ansible.builtin.wait_for_connection:
                timeout: 3
              check_mode: false
          rescue:
            - name: Define creds_status
              ansible.builtin.set_fact:
                creds_status: 'The VM credentials are invalid'
    - name: Assert that credentials are valid
      ansible.builtin.assert:
        that:
          - creds_status | default('') is not search('invalid')
          - creds_status | default('') is not search('does not exist')
        fail_msg: "{{ creds_status | default('') }}"
    - name: Joining domain
      when: join_domain | default(false)
      block:
        - name: Update hostname
          ansible.builtin.include_tasks: task_update_hostname.yml
        - name: Join domain
          ansible.builtin.include_tasks: task_join_domain.yml
    - name: Leave domain
      ansible.builtin.include_tasks: task_leave_domain.yml
      when: leave_domain | default(false)
