---
# Tasks to install LDAP needed packages
- block:
  - name: Install LDAP needed packages
    ansible.builtin.yum:
      name:
        - realmd
        - oddjob
        - oddjob-mkhomedir
        - sssd
        - adcli
        - openldap-clients
        - samba-common
        - samba-common-tools
        - krb5-workstation
      state: installed
  become: true
  tags: [ 'never', 'ldap_integration' ]
