---
# Tasks to configure the hostname
- name: Configure hostname
  become: true
  block:
    - name: Get current hostname
      ansible.builtin.command: hostname
      register: reg_hostname
      changed_when: false
      check_mode: false
    - name: Set the hostname with a domain
      ansible.builtin.command: |
        hostnamectl set-hostname {{ fqn }}
      when: reg_hostname.stdout != fqn
      register: set_hostname
      changed_when: set_hostname.rc == 0
      vars:
        fqn: "{{ vm.name }}.{{ sysconfig.secondary.domain_name if 'dr' in group_names else sysconfig.primary.domain_name }}"
    - name: Update hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ myaddress }}   {{ vm.name }} {{ vm.name }}.{{ mydomain }}"
      vars:
        myaddress: "{{ netconfig.nic1.ipaddress if vm.name is not search('csr') else netconfig.nic3.ipaddress }}"
        mydomain: "{{ sysconfig.secondary.domain_name if 'dr' in group_names else sysconfig.primary.domain_name }}"
