---
- name: define capcheck
  ansible.builtin.set_fact:
    capcheck: true
  when:
    - deploy | default(false) | bool
    - "'vcenter' in group_names or (build.disaster_recovery and 'drvcenter' in group_names)"
  tags: [ 'capcheck', 'vm_creation' ]
  
- name: define create_vms_iso
  ansible.builtin.set_fact:
    create_vms_iso: true
  when:
    - deploy | default(false) | bool
    - "'stack' in group_names or (build.disaster_recovery and 'dr' in group_names)"
  tags: vm_creation

- name: define rollback_vms_iso
  ansible.builtin.set_fact:
    rollback_vms_iso: true
  when:
    - rollback | default(false) | bool
    - "'stack' in group_names or (build.disaster_recovery and 'dr' in group_names)"
  tags: vm_creation

- name: define harden_vms
  ansible.builtin.set_fact:
    harden_vms: true
  when:
    - deploy | default(false) | bool
    - "'stack' in group_names or (build.disaster_recovery and 'dr' in group_names)"
    - build.version.os_iso|lower is search('centos')
  tags: vm_hardening

- name: define install_docker
  ansible.builtin.set_fact:
    install_docker: true
  when:
    - deploy | default(false) | bool
    - "'stack' in group_names or (build.disaster_recovery and 'dr' in group_names)"
  tags: [ 'never', 'docker' ]
