---
# tasks file to install the desktop package
- name: Install desktop manager
  when: ansible_facts.distribution == 'Ubuntu'
  become: "{{ true if ansible_user != 'root' else false }}"
  block:
    - name: Update and upgrade
      ansible.builtin.apt:
        name: '*'
        state: latest # noqa: package-latest
        update_cache: true
    - name: Install the ubuntu-desktop packages
      ansible.builtin.apt:
        pkg:
          - ubuntu-desktop
          - xfce4
          - xfce4-goodies
          - gdm3
          - xrdp
        state: present
      notify:
        - Start and enable services
        - Reboot vm
    - name: Allow access to RDP port 3389
      community.general.ufw:
        rule: allow
        port: '3389'
        proto: tcp
    - name: Change setings in /etc/sssd/sssd.conf
      ansible.builtin.replace:
        path: '/etc/sssd/sssd.conf'
        regexp: '^({{ line_item.param }} =).*$'
        replace: '\g<1> {{ line_item.value }}'
      loop:
        - { param: 'access_provider', value: 'simple' }
      loop_control:
        loop_var: line_item
      notify: Restart sssd
    - name: Define xfce4 as the default XSession type
      ansible.builtin.copy:
        dest: /etc/profile.d/setxsession.sh
        content: 'echo "xfce4-session" > ${HOME}/.xsession'
        mode: '644'
    - name: Set the number of xfce4 workspaces to 1
      ansible.builtin.replace:
        path: /usr/share/xfwm4/defaults
        regexp: '^(workspace_count=).*$'
        replace: '\g<1>1'
    - name: Fix authentication is required popup
      ansible.builtin.copy:
        dest: /etc/polkit-1/localauthority/50-local.d/45-allow-colord.pkla
        content: '[Allow Colord all Users]\nIdentity=unix-user:*\nAction=org.freedesktop.color-manager.create-device;org.freedesktop.color-manager.create-profile;org.freedesktop.color-manager.delete-device;org.freedesktop.color-manager.delete-profile;org.freedesktop.color-manager.modify-device;org.freedesktop.color-manager.modify-profile\nResultAny=no\nResultInactive=no\nResultActive=yes' # noqa: yaml[line-length]
        mode: '644'
    - name: Copy XFCE applications menu customization file
      ansible.builtin.copy:
        dest: /etc/skel/.config/menus/
        src: "{{ role_path }}/files/xfce-applications.menu"
        mode: '644'
    - name: Start terminal-emulator at startup
      ansible.builtin.copy:
        remote_src: true
        dest: /etc/skel/.config/autostart/
        src: /usr/share/applications/xfce4-terminal-emulator.desktop
        mode: '644'
    - name: Create the XFCE applications menu customization script
      ansible.builtin.copy:
        dest: /etc/profile.d/setxfce_app_menu.sh
        src: "{{ role_path }}/files/setxfce_app_menu.sh"
        mode: '644'
    - name: Enable scripts under /etc/profile.d/ are executed with non-login interactive shells
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker_begin: 'BEGIN PROFILE.D EXECUTION'
        marker_end: 'END PROFILE.D EXECUTION'
        marker: '# {mark}'
        block: |
          if [ -d /etc/profile.d ]; then
            for i in /etc/profile.d/*.sh; do
              if [ -r $i ]; then
                . $i
              fi
            done
            unset i
          fi
