---
# tasks file to remove the desktop package
- name: Remove desktop package
  when: ansible_facts.distribution == 'Ubuntu'
  become: "{{ true if ansible_user != 'root' else false }}"
  block:
    - name: Undefine xfce4 as the default XSession type
      ansible.builtin.file:
        path: /etc/profile.d/setxsession.sh
        state: absent
    - name: Remove the XFCE applications menu customization files
      ansible.builtin.file:
        path: "{{ file_item }}"
        state: absent
      loop:
        - /etc/skel/.config
        - /etc/profile.d/setxfce_app_menu.sh
      loop_control:
        loop_var: file_item
    - name: Disable scripts under /etc/profile.d/ are executed with non-login interactive shells
      ansible.builtin.blockinfile:
        path: /etc/bash.bashrc
        marker_begin: 'BEGIN PROFILE.D EXECUTION'
        marker_end: 'END PROFILE.D EXECUTION'
        marker: '# {mark}'
        state: absent
    - name: Remove the ubuntu-desktop packages
      ansible.builtin.apt:
        pkg:
          - ubuntu-desktop
          - xfce4
          - xfce4-goodies
          - gdm3
          - xrdp
        state: absent
      notify:
        - Reboot vm
