---
# handlers file for ldap_integration
- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    daemon_reload: true
  become: "{{ true if ansible_user != 'root' else false }}"

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    daemon_reload: true
  become: "{{ true if ansible_user != 'root' else false }}"
