---
# handlers file for ldap_integration
- name: restart sssd
  systemd:
    name: sssd
    state: restarted
    daemon_reload: yes
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'ldap_integration' ]
