---
# handlers file for vm_fromiso
- name: restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    daemon_reload: yes
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: expand disk0
  ansible.builtin.shell: |
    for BUS in /sys/class/scsi_disk/*/device/rescan; do echo 1 > ${BUS}; done
    echo -e "d\n3\nn\np\n3\n\n\nw\n" | fdisk /dev/sda
    echo -e "d\n3\nn\n3\n\n\nw\n" | fdisk /dev/sda
    partprobe
    {% if build.version.os_iso|lower is search('ubuntu') %}
    resize2fs $(df | grep ' /$' | awk '{print $1}')
    {% else %}
    xfs_growfs $(grep ' / ' /etc/fstab | awk '{print $2}')
    {% endif %}
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: reboot vm
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 60
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: expand disk1
  ansible.builtin.shell: |
    FSTYPE='{% if build.version.os_iso|lower is search('ubuntu') %}ext4{% else %}xfs{% endif %}'
    mp1=$(df -h | grep sdb1 | awk '{print $NF}')
    umount ${mp1}
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    [[ "${mp1}" != "{{ vm.disk1_mount }}" ]] && mv ${mp1} {{ vm.disk1_mount }}
    for BUS in /sys/class/scsi_disk/*/device/rescan; do echo 1 > ${BUS}; done
    parted -s /dev/sdb resizepart 1 100%
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    disk1_uuid=$(blkid | grep sdb1 | awk '{print $2}' | sed 's|"||g')
    sed -i "s|^\(.*${disk1_uuid}\) /[[:alnum:]]* ${FSTYPE}|\1 {{ vm.disk1_mount }} ${FSTYPE}|" /etc/fstab
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    mount -a
    {% if build.version.os_iso|lower is search('ubuntu') %}
    resize2fs {{ vm.disk1_mount }}
    {% else %}
    xfs_growfs -d {{ vm.disk1_mount }}
    {% endif %}
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: add disk1
  ansible.builtin.shell: |
    for BUS in /sys/class/scsi_host/host*/scan; do echo "- - -" > ${BUS}; done
    echo -e "n\np\n\n\n\nw\n" | fdisk /dev/sdb
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: create disk1 filesystem
  tags: vm_creation

- name: create disk1 filesystem
  ansible.builtin.filesystem:
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    device: /dev/sdb1
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: get disk1 UUID
  tags: vm_creation

- name: get disk1 UUID
  ansible.builtin.shell: |
    blkid | grep sdb1 | awk '{print $2}' | sed 's|"||g'
  register: reg_disk1_uuid
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set disk1 mount points
  tags: vm_creation

- name: set disk1 mount points
  ansible.posix.mount:
    name: "{{ vm.disk1_mount }}"
    src: "{{ '/dev/disk/by-uuid/' + reg_disk1_uuid.stdout|replace('UUID=','') else reg_disk1_uuid.stdout }}"
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    opts: defaults
    state: mounted
    dump: '1'
    passno: '2'
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set permissions and ownership of disk1
  tags: vm_creation

- name: set permissions and ownership of disk1
  ansible.builtin.file:
    path: "{{ vm.disk1_mount }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: expand disk2
  ansible.builtin.shell: |
    FSTYPE='{% if build.version.os_iso|lower is search('ubuntu') %}ext4{% else %}xfs{% endif %}'
    mp2=$(df -h | grep sdc1 | awk '{print $NF}')
    umount ${mp2}
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    [[ "${mp2}" != "{{ vm.disk2_mount }}" ]] && mv ${mp2} {{ vm.disk2_mount }}
    for BUS in /sys/class/scsi_disk/*/device/rescan; do echo 1 > ${BUS}; done
    parted -s /dev/sdc resizepart 1 100%
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    disk2_uuid=$(blkid | grep sdc1 | awk '{print $2}' | sed 's|"||g')
    sed -i "s|^\(.*${disk2_uuid}\) /[[:alnum:]]* ${FSTYPE}|\1 {{ vm.disk2_mount }} ${FSTYPE}|" /etc/fstab
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    mount -a
    {% if build.version.os_iso|lower is search('ubuntu') %}
    resize2fs {{ vm.disk2_mount }}
    {% else %}
    xfs_growfs -d {{ vm.disk2_mount }}
    {% endif %}
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: add disk2
  ansible.builtin.shell: |
    for BUS in /sys/class/scsi_host/host*/scan; do echo "- - -" > ${BUS}; done
    echo -e "n\np\n\n\n\nw\n" | fdisk /dev/sdc
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: create disk2 filesystem
  tags: vm_creation

- name: create disk2 filesystem
  ansible.builtin.filesystem:
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    device: /dev/sdc1
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: get disk2 UUID
  tags: vm_creation

- name: get disk2 UUID
  ansible.builtin.shell: |
    blkid | grep sdc1 | awk '{print $2}' | sed 's|"||g'
  register: reg_disk2_uuid
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set disk2 mount points
  tags: vm_creation

- name: set disk2 mount points
  ansible.posix.mount:
    name: "{{ vm.disk2_mount }}"
    src: "{{ '/dev/disk/by-uuid/' + reg_disk2_uuid.stdout|replace('UUID=','') else reg_disk2_uuid.stdout }}"
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    opts: defaults
    state: mounted
    dump: '1'
    passno: '2'
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set permissions and ownership of disk2
  tags: vm_creation

- name: set permissions and ownership of disk2
  ansible.builtin.file:
    path: "{{ vm.disk2_mount }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: expand disk3
  ansible.builtin.shell: |
    FSTYPE='{% if build.version.os_iso|lower is search('ubuntu') %}ext4{% else %}xfs{% endif %}'
    mp3=$(df -h | grep sdd1 | awk '{print $NF}')
    umount ${mp3}
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    [[ "${mp3}" != "{{ vm.disk3_mount }}" ]] && mv ${mp3} {{ vm.disk3_mount }}
    for BUS in /sys/class/scsi_disk/*/device/rescan; do echo 1 > ${BUS}; done
    parted -s /dev/sdd resizepart 1 100%
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    disk3_uuid=$(blkid | grep sdd1 | awk '{print $2}' | sed 's|"||g')
    sed -i "s|^\(.*${disk3_uuid}\) /[[:alnum:]]* ${FSTYPE}|\1 {{ vm.disk3_mount }} ${FSTYPE}|" /etc/fstab
    {{ 'sleep 2' if build.version.os_iso|lower is search('centos') else '' }}
    mount -a
    {% if build.version.os_iso|lower is search('ubuntu') %}
    resize2fs {{ vm.disk3_mount }}
    {% else %}
    xfs_growfs -d {{ vm.disk3_mount }}
    {% endif %}
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation

- name: add disk3
  ansible.builtin.shell: |
    for BUS in /sys/class/scsi_host/host*/scan; do echo "- - -" > ${BUS}; done
    echo -e "n\np\n\n\n\nw\n" | fdisk /dev/sdd
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: create disk3 filesystem
  tags: vm_creation

- name: create disk3 filesystem
  ansible.builtin.filesystem:
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    device: /dev/sdd1
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: get disk3 UUID
  tags: vm_creation

- name: get disk3 UUID
  ansible.builtin.shell: |
    blkid | grep sdd1 | awk '{print $2}' | sed 's|"||g'
  register: reg_disk3_uuid
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set disk3 mount points
  tags: vm_creation

- name: set disk3 mount points
  ansible.posix.mount:
    name: "{{ vm.disk3_mount }}"
    src: "{{ '/dev/disk/by-uuid/' + reg_disk3_uuid.stdout|replace('UUID=','') else reg_disk3_uuid.stdout }}"
    fstype: "{{ 'ext4' if build.version.os_iso|lower is search('ubuntu') else 'xfs' }}"
    opts: defaults
    state: mounted
    dump: '1'
    passno: '2'
  become: "{{ true if ansible_user != 'root' else false }}"
  notify: set permissions and ownership of disk3
  tags: vm_creation

- name: set permissions and ownership of disk3
  ansible.builtin.file:
    path: "{{ vm.disk3_mount }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: vm_creation
