---
# Tasks to create the Packer builder file
- block:
  - name: get ISO info
    stat:
      path: "{{ auto_dir }}/{{ iso_dir }}/{{ iso_installer }}"
      checksum_algorithm: sha512
      get_checksum: yes
    register: iso_info
    run_once: true
  - ansible.builtin.assert:
      that: iso_info.stat.exists
      fail_msg: "{{ auto_dir }}/{{ iso_dir }}/{{ iso_installer }} is not found" 
  - name: Create Packer builder
    template:
      src: "templates/ubuntu.json.j2"
      dest: "{{ role_path }}/files/{{ vm.name }}-builder.json"
  delegate_to: localhost
  tags: vm_creation
