---
# Tasks to copy the ISO file to datastore
- name: Copying autoinstall ISO to Vsphere
  vars:
    mystorage_ds: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_datastore'] }}"
    mystorage_path: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['storage_path'] }}"
  delegate_to: localhost
  environment:
    http_proxy: ''
    https_proxy: ''
  block:
    - name: Define iso_datastore and iso_path
      ansible.builtin.set_fact:
        iso_datastore: "{{ mystorage_ds if mystorage_ds != '' else vm_ds }}"
        iso_path: "ISO{{ '/' + mystorage_path if mystorage_path != '' else '' }}"
    - name: Create a directory on the datastore
      community.vmware.vsphere_file:
        hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
        username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
        password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
        datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
        datastore: "{{ iso_datastore }}"
        path: "{{ iso_path }}"
        state: directory
        validate_certs: false
      register: ds_folder
      throttle: 1
    - name: Copying ISO file to Vsphere
      when: ds_folder is succeeded
      block:
        - name: Poweroff VM
          ansible.builtin.include_tasks: task_poweroff_vm.yml
        - name: Copy Autoinstall ISO file to vsphere
          community.vmware.vsphere_copy:
            hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
            username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
            password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
            datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
            datastore: "{{ iso_datastore }}"
            src: "{{ role_path }}/files/{{ vm.name }}-tmpdir/{{ (build.version.os_iso | split('-'))[:2] | join('-') + '-autoinstall.iso' }}"
            path: "{{ iso_path }}/{{ vm.name }}-autoinstall.iso"
            validate_certs: false
          async: 7200
          poll: 30
