---
# Tasks to unpack Ubuntu ISO file
- name: Unpack Ubuntu ISO file
  delegate_to: localhost
  block:
    - name: Create temporary directory structure
      ansible.builtin.file:
        path: "{{ role_path }}/files/{{ vm.name }}-tmpdir/source_files/server"
        state: directory
        mode: '777'
    - name: Unpack ISO
      ansible.builtin.shell: |
        7z -y x {{ auto_dir }}/{{ iso_dir }}/{{ build.version.os_iso }} -osource_files
        chmod -R go+rwx source_files
      args:
        chdir: "{{ role_path }}/files/{{ vm.name }}-tmpdir"
      register: unpack_iso
      changed_when: unpack_iso.rc == 0
    - name: Move '[BOOT]' directory to ../BOOT
      ansible.builtin.shell: |
        rm -rf ../BOOT; mv -f \[BOOT\] ../BOOT
      args:
        chdir: "{{ role_path }}/files/{{ vm.name }}-tmpdir/source_files"
      register: move_boot
      changed_when: move_boot.rc == 0
