---
# Tasks to create the Ubuntu autoinstall data files
- name: Creating Ubuntu autoinstall data files
  delegate_to: localhost
  block:
    - name: Create Ubuntu meta-data file
      ansible.builtin.file:
        path: "{{ role_path }}/files/{{ vm.name }}-tmpdir/source_files/server/meta-data"
        state: touch
        mode: '644'
    - name: Create Ubuntu user-data file
      ansible.builtin.template:
        src: "templates/ubuntu_user-data.tmpl"
        dest: "{{ role_path }}/files/{{ vm.name }}-tmpdir/source_files/server/user-data"
        mode: '644'
