---
# Tasks to create and configure VM pairs
- block:
  - name: "vm_creation: get vm datastore"
    include_role:
      name: vm_creation
      tasks_from: task_get_vm_datastore.yml
    when:
      - hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datastore_cluster'] == '' or (inventory_hostname is search('em7') and hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['deptype'] == 'h')

  - include_tasks: task_create_packer_builder.yml
    when: inventory_hostname is search('em7')

  - block:
    - include_tasks: task_create_kickstart_iso.yml
    - include_tasks: task_copy_kickstart_iso_to_vsphere.yml
    - include_tasks: task_deploy_iso_self_healing.yml
    - name: "vm_creation: Update custom attributes"
      include_role:
        name: vm_creation
        tasks_from: task_update_custom_attributes.yml
    - include_tasks: task_delete_gtw_nic1_self_healing.yml
    - include_tasks: task_update_disks_self_healing.yml
    - include_tasks: task_delete_kickstart_files.yml
    when: inventory_hostname is not search('em7')

  - block:
    - include_tasks: task_deploy_em7iso.yml
    - name: "vm_creation: Update custom attributes"
      include_role:
        name: vm_creation
        tasks_from: task_update_custom_attributes.yml
    - include_tasks: task_update_em7prt_disk0.yml
    - include_tasks: task_reboot_vm.yml
      when: vmguest_disk0 is changed
    - include_tasks: task_rename_nic2_self_healing.yml
      when: inventory_hostname is not search('em7mc')
    when: inventory_hostname is search('em7')

  - include_tasks: task_update_default_route.yml
  - include_tasks: task_add_gtw2.yml

  - block:
    - include_tasks: task_add_ipv6.yml
    - include_tasks: task_expand_fs.yml
    - include_tasks: task_delete_packer_builder.yml
    - include_tasks: task_upgrade_mariadb.yml
      when: groups['em7']|length > 1 and inventory_hostname is search('em7db') or groups['em7']|length == 1
    when: inventory_hostname is search('em7')
  
  - name: flush handlers
    meta: flush_handlers
  tags: vm_creation
