---
# Tasks to create the Packer builder file
- block:
  - name: get ISO info
    stat:
      path: "{{ auto_dir }}/{{ iso_dir }}/{{ iso_installer }}"
      checksum_algorithm: sha512
      get_checksum: yes
    register: iso_info
    run_once: true
  - ansible.builtin.assert:
      that: iso_info.stat.exists
      fail_msg: "{{ auto_dir }}/{{ iso_dir }}/{{ iso_installer }} is not found" 
  - name: Create Packer builder
    template:
      src: "templates/build-{{ inventory_hostname[:-2] | regex_replace('drem7', 'em7') }}.json.j2"
      dest: "{{ role_path }}/files/{{ vm.name }}-builder.json"
  delegate_to: "{{ groups['bastion'][0] if (groups['bastion'] | length >= 1 and bastion.address != [] and bastion.address != ['']) else 'localhost' }}"
  tags: vm_creation
