---
# tasks to update VM's custom attributes
- block:
  - name: get date and user's email address
    ansible.builtin.shell: |
      date '+%F'
      git config user.email
    register: reg_user_email
    check_mode: no
  - name: Add VM's custom attributes
    community.vmware.vmware_guest_custom_attributes:
      hostname: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['address'] }}"
      username: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['username'] }}"
      password: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['credentials']['password'] }}"
      datacenter: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] }}"
      folder: "{{ hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datacenter'] + '/vm' + ('/' + fldr_name if fldr_name != '' else '') }}"
      name: "{{ vm.name }}"
      state: present
      attributes:
        - name: date-created
          value: "{{ reg_user_email.stdout_lines|first }}"
        - name: team-contact1
          value: "{{ reg_user_email.stdout_lines|last }}"
      validate_certs: no
    register: reg_add_attribute
    ignore_errors: true
  - debug:
      msg:
        - 'The automation user does not have sufficient privileges to modify custom attributes'
    when:
        - reg_add_attribute is search('Permission to perform this operation was denied')
  delegate_to: "{{ groups['bastion'][0] if (groups['bastion'] | length >= 1 and bastion.address != [] and bastion.address != ['']) else 'localhost' }}"
  tags: vm_creation
