---
# Tasks to create and configure VM pairs
- block:
  - include_tasks: task_get_vm_datastore.yml
    when:
      - hostvars[groups[('dr' if 'dr' in group_names else '') + 'vcenter'][0]]['information']['datastore_cluster'] == ''
      - vm_ds is not defined or vm_ds == ''
  - include_tasks: task_deploy_ova.yml
  - include_tasks: task_update_custom_attributes.yml
  - include_tasks: task_update_disks_self_healing.yml
  - include_tasks: task_update_hardware.yml
  - include_tasks: task_enable_root_login.yml
  - include_tasks: task_delete_gtw_from_network_file_self_healing.yml
  - include_tasks: task_update_default_route.yml
  - include_tasks: task_rename_interface.yml
  - include_tasks: task_update_vmwaretools.yml
  tags: vm_creation
