---
# tasks file to remove the connector package
- block:
  - name: remove the amp connector package
    ansible.builtin.apt:
      name: ciscoampconnector
      state: absent
    when: ansible_facts.distribution == 'Ubuntu'
  - name: remove the amp connector package
    ansible.builtin.dnf:
      name: ciscoampconnector
      state: absent
    when: ansible_facts.distribution == 'AlmaLinux'
  - name: remove the amp connector package
    ansible.builtin.yum:
      name: ciscoampconnector
      state: absent
    when: ansible_facts.distribution == 'CentOS'
  become: "{{ true if ansible_user != 'root' else false }}"
