---
# tasks file to remove the connector package
- name: Removing connector package
  become: "{{ true if ansible_user != 'root' else false }}"
  block:
    - name: Remove the amp connector package
      ansible.builtin.apt:
        name: ciscoampconnector
        state: absent
      when: ansible_facts.distribution == 'Ubuntu'
    - name: Remove the amp connector package
      ansible.builtin.dnf:
        name: ciscoampconnector
        state: absent
      when: ansible_facts.distribution == 'AlmaLinux'
    - name: Remove the amp connector package
      ansible.builtin.yum:
        name: ciscoampconnector
        state: absent
      when: ansible_facts.distribution == 'CentOS'
