---
# Tasks to enable no-password sudo
- name: Enable no-password sudo
  become: "{{ true if ansible_user != 'root' else false }}"
  block:
    - name: Enable no-password sudo commands for {{ vm_admin_user }}
      ansible.builtin.replace:
        path: "/etc/sudoers.d/{{ vm_admin_user }}"
        regexp: '^(%.*\)) ({{ vm_admin_user | upper }}.*)$'
        replace: '\g<1> NOPASSWD: \g<2>'
    - name: Check if domain is joined
      ansible.builtin.command: realm list
      register: reg_joined
      changed_when: false
      failed_when: reg_joined.stdout_lines | select('search','realm-name') | list == []
      check_mode: false
      ignore_errors: true
    - name: Allow domain users to do no-password sudo
      when: reg_joined is succeeded
      block:
        - name: Check if domain users are allowed to do no password sudo
          ansible.builtin.lineinfile:
            path: /etc/sudoers
            line: '%domain\ users        ALL=(ALL)       NOPASSWD: ALL'
          check_mode: true
          register: reg_ds_check
          failed_when: reg_ds_check is failed or reg_ds_check is changed
      rescue:
        - name: Allow domain users to do no password sudo
          ansible.builtin.replace:
            path: /etc/sudoers
            regexp: '^{{ line_item.reg }}$'
            replace: '{{ line_item.rep }}'
            validate: /usr/sbin/visudo -cf %s
          loop:
            - { reg: '(## Allows members of the "domain users" group to run all commands)', rep: '\g<1> without a password' }
            - { reg: '(%domain.+users\s+ALL=.ALL.\s+)ALL', rep: '\g<1>NOPASSWD: ALL' }
          loop_control:
            loop_var: line_item
