---
# Tasks to enable no-password sudo
- block:
  - name: enable no-password sudo commands
    ansible.builtin.replace:
      path: "/etc/sudoers.d/{{ vm_admin_user }}"
      regexp: '^(%.*\)) ({{ vm_admin_user|upper }}.*)$'
      replace: '\g<1> NOPASSWD: \g<2>'
    become: true
  tags: [ 'never', 'docker' ]
