---
# Tasks to install Docker
- block:
  - name: get the Linux distribution
    ansible.builtin.setup:
      filter:
        - 'ansible_distribution'
  - block:
    - name: Install Podman-Docker
      ansible.builtin.yum:
        name: 'podman-docker'
        state: installed
    - name: create the /etc/containers/nodocker file
      ansible.builtin.file:
        path: /etc/containers/nodocker
        state: touch
    when: ansible_facts.distribution == 'AlmaLinux'
    become: true
  - name: Install Docker
    ansible.builtin.yum:
      name: 'docker'
      state: installed
    notify:
      - create docker group
      - add user to docker group
      - create docker service directory
      - add proxy to docker
      - start docker
      - reboot the node
    when: ansible_facts.distribution == 'CentOS'
    become: true
  tags: [ 'never', 'docker' ]
