---
# Tasks to install Docker
- name: Install Docker/Podman-Docker
  become: true
  block:
    - name: Get the Linux distribution
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
    - name: Install Podman-Docker on AlmaLinux
      when: ansible_facts.distribution == 'AlmaLinux'
      block:
        - name: Install Podman-Docker
          ansible.builtin.yum:
            name: 'podman-docker'
            state: installed
        - name: Create the /etc/containers/nodocker file
          ansible.builtin.file:
            path: /etc/containers/nodocker
            state: touch
            mode: '644'
        - name: Set ignore_chown_errors to true in /etc/containers/storage.conf
          ansible.builtin.replace:
            path: /etc/containers/storage.conf
            regexp: '^(ignore_chown_errors =) "false"$'
            replace: '\g<1> "true"'
        - name: Define REGISTRY_AUTH_FILE
          ansible.builtin.lineinfile:
            line: "{{ line_item.toadd }}"
            path: "{{ line_item.filename }}"
          loop:
            - {filename: '/etc/environment', toadd: 'export REGISTRY_AUTH_FILE="${HOME}/.podman/auth.json"'}
            - {filename: '/etc/bashrc', toadd: 'source /etc/environment'}
          loop_control:
            loop_var: line_item
    - name: Install Docker on CentOS
      ansible.builtin.yum:
        name: 'docker'
        state: installed
      notify:
        - Create docker group
        - Add user to docker group
        - Create docker service directory
        - Add proxy to docker
        - Start docker
        - Reboot the node
      when: ansible_facts.distribution == 'CentOS'
    - name: Install Podman=Docker on Ubuntu
      when: ansible_facts.distribution == 'Ubuntu'
      block:
        - name: Install Podman-Docker
          ansible.builtin.apt:
            name: 'podman-docker'
            state: present
            update_cache: true
        - name: Create the /etc/containers/nodocker file
          ansible.builtin.file:
            path: /etc/containers/nodocker
            state: touch
            mode: '644'
