---
# handlers file for udesktop
- name: start and enable services
  systemd:
    name: "{{ svc_item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop:
    - gdm
    - xrdp
  loop_control:
    loop_var: svc_item
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'udesktop' ]

- name: restart sssd
  systemd:
    name: sssd
    state: restarted
    daemon_reload: yes
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'udesktop' ]

- name: reboot vm
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 60
  become: "{{ true if ansible_user != 'root' else false }}"
  tags: [ 'never', 'udesktop' ]
