---
# handlers file for udesktop
- name: Start and enable services
  ansible.builtin.systemd:
    name: "{{ svc_item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - gdm
    - xrdp
  loop_control:
    loop_var: svc_item
  become: "{{ true if ansible_user != 'root' else false }}"

- name: Restart sssd
  ansible.builtin.systemd:
    name: sssd
    state: restarted
    daemon_reload: true
  become: "{{ true if ansible_user != 'root' else false }}"

- name: Reboot vm
  ansible.builtin.reboot:
    post_reboot_delay: 10
    reboot_timeout: 60
  become: "{{ true if ansible_user != 'root' else false }}"
