---
# Validate credentials (always run)
- name: Validate credentials
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  roles:
    - role: check_creds

# Play to determine what to do and to define vm facts(always run)
- name: Define variables
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  roles:
    - role: todo
    - role: vm_facts

# Play to perform the infrastructure capacity check
- name: Pre-deploy preparation
  hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  gather_facts: false

  tasks:
    - block:
      - ansible.builtin.include_role:
          name: capcheck
        when: capcheck | default(false) | bool
        tags: ['capcheck', 'vm_creation']
      - ansible.builtin.include_role:
          name: infra_dns_records
        when: add_dns_records | default(false) | bool
        tags: [ 'infra_dns_records', 'vm_creation' ]
      when: deploy | default(false) | bool

# Play to create the VMs
- name: Deploy VMs
  hosts: all
  strategy: free
  gather_facts: false

  tasks:
    - block:
      - ansible.builtin.include_role:
          name: vm_fromiso
        when: create_vms_iso | default(false) | bool
        tags: vm_creation
      when: deploy | default(false) | bool

# Play to configure the VMs
- name: Configure VMs
  hosts: all
  gather_facts: false

  tasks:
    - block:
      - ansible.builtin.include_role:
          name: vm_hardening
        when: harden_vms | default(false) | bool
        tags: vm_hardening
      - ansible.builtin.include_role:
          name: ldap_integration
        when: join_domain | default(false) | bool
        tags: [ 'never', 'ldap_integration' ]
      - ansible.builtin.include_role:
          name: docker
        when: install_docker | default(false) | bool
        tags: [ 'never', 'docker' ]
      - ansible.builtin.include_role:
          name: usrquota
        when: set_quota | default(false) | bool
        tags: [ 'never', 'usrquota' ]
      - ansible.builtin.include_role:
          name: amp_connector
        when: install_connector | default(false) | bool
        tags: [ 'never', 'amp_connector' ]
      - ansible.builtin.include_role:
          name: udesktop
        when: install_desktop | default(false) | bool
        tags: [ 'never', 'udesktop' ]
      when: deploy | default(false) | bool

# Play to delete the VMs
- name: Rollback VMs
  hosts: all
  order: reverse_inventory
  gather_facts: false

  tasks:
    - block:
      - ansible.builtin.include_role:
          name: udesktop
        when: remove_desktop | default(false) | bool
        tags: [ 'never', 'udesktop' ]
      - ansible.builtin.include_role:
          name: amp_connector
        when: remove_connector | default(false) | bool
        tags: [ 'never', 'amp_connector' ]
      - ansible.builtin.include_role:
          name: usrquota
        when: unset_quota | default(false) | bool
        tags: [ 'never', 'usrquota' ]
      - ansible.builtin.include_role:
          name: ldap_integration
        when: leave_domain | default(false) | bool
        tags: [ 'never', 'ldap_integration' ]
      - ansible.builtin.include_role:
          name: vm_fromiso
        when: rollback_vms_iso | default(false) | bool
        tags: vm_creation
      - ansible.builtin.include_role:
          name: infra_dns_records
        when: rollback_dns_records | default(false) | bool
        tags: [ 'infra_dns_records', 'vm_creation' ]
      when: rollback | default(false) | bool
